# Generated by Django 4.2.2 on 2023-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.ImageField(upload_to='pan')),
                ('selfie', models.ImageField(upload_to='selfie')),
            ],
        ),
    ]
