# Generated by Django 4.2.2 on 2023-06-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_face_rec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognization',
            name='name',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
